name: Compile LaTeX

on:
  push:
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compiler le fichier LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: eco-EPL1803-summary.tex  # Mets le nom exact de ton fichier ici
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: document-pdf
          path: eco-EPL1803-summary.pdf  # Nom du fichier généré
